#datasource
#这里配的是我本机的数据库 mysql+redis
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/datasci?useSSL=false
    username: root
    password: 888888
    driver-class-name: com.mysql.cj.jdbc.Driver

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB
      #文件保存路径
      location: 'D:\\java\DataSci\\lqf\\JudicatureAutoLabel\\project-dev\\judicature\\src\\main\\resources\\case\\'


  mvc:
    view:
      prefix:
      suffix:

  redis:
    host: 127.0.0.1
    port: 6379
  #thymeleaf:
  #  prefix: classpath:/template/
  #  suffix: .html

#映射文件方式
mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml #mapper的映射文件路径
  type-aliases-package: DataSci.judicature.domain #配置别名扫描
  config-location: classpath:sqlMapConfig.xml   #指定核心配置文件

server:
  port: 80
  servlet:
    encoding:
      charset: utf-8

#当前项目在本机的真实路径
PATH: 'D:\\java\DataSci\\lqf\\JudicatureAutoLabel\\project-dev\\judicature\\'