##################
## 多文档方式配置 ##
##################

# 使用开发环境
spring:
  profiles:
    active: dev

---

#开发环境
#没有使用数据库

spring:
  config:
    activate:
      on-profile: dev
  mvc:
    view:
      prefix:
      suffix:

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB
      #文件保存路径
      location: ${PATH}project-dev\\judicature\\src\\main\\resources\\case\\
      #thymeleaf:
      #  prefix: classpath:/template/
      #  suffix: .html


server:
  port: 80
  servlet:
    encoding:
      charset: utf-8


#当前项目在本机的真实路径
PATH: 'D:\\java\\DataSci\\lqf\\JudicatureAutoLabel\\'


---

#生产环境

#datasource
#这里配的是我本机的数据库 mysql+redis
spring:
  config:
    activate:
      on-profile: pro

  datasource:
    url: jdbc:mysql://localhost:3306/datasci?useSSL=false
    username: root
    password: 888888
    driver-class-name: com.mysql.cj.jdbc.Driver

  redis:
    host: 127.0.0.1
    port: 6379


#映射文件方式
mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml #mapper的映射文件路径
  type-aliases-package: DataSci.judicature.domain #配置别名扫描
  config-location: classpath:sqlMapConfig.xml   #指定核心配置文件

